config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'

  resources :heros, only: [:create, :index]

  resources :users, only: [:create, :new, :show, :update] do
    get '/settings', to: 'settings#show'
  end
  get '/dashboard', to: 'users#show'
  get '/explanations', to: 'explanations#show'
  post '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hero.rb
class Hero < ApplicationRecord

  def first_pick_percent
    ((one_pick.to_f / total_picks) * 100).round(2)
  end

  def first_win_percent
    ((one_win.to_f / one_pick) * 100).round(2)
  end

  def second_pick_percent
    ((two_pick.to_f / total_picks) * 100).round(2)
  end

  def second_win_percent
    ((two_win.to_f / two_pick) * 100).round(2)
  end

  def third_pick_percent
    ((three_pick.to_f / total_picks) * 100).round(2)
  end

  def third_win_percent
    ((three_win.to_f / three_pick) * 100).round(2)
  end

  def fourth_pick_percent
    ((four_pick.to_f / total_picks) * 100).round(2)
  end

  def fourth_win_percent
    ((four_win.to_f / four_pick) * 100).round(2)
  end

  def fifth_pick_percent
    ((five_pick.to_f / total_picks) * 100).round(2)
  end

  def fifth_win_percent
    ((five_win.to_f / five_pick) * 100).round(2)
  end

  def total_picks
    one_pick + two_pick + three_pick + four_pick + five_pick
  end

  def win_rate
    (((one_win + two_win + three_win + four_win + five_win) / total_picks) * 100).round(2)
  end

  def total_pro_participation
    pro_pick + pro_ban
  end

end

app/models/user.rb
class User < ApplicationRecord

  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth[:uid]
      user.name = auth[:info][:nickname]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/explanations_controller.rb
class ExplanationsController < ApplicationController

  def show

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def create
    auth = request.env['omniauth.auth']
    user = User.find_by_uid(auth['uid']) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    flash[:notice] = "Signed In As #{user.name}"
    redirect_to dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def show
    @user = current_user
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(session[:user_id])
    @steam_user = SteamUserPresenter.new(user)
  end

  def update
    user = current_user
    if !params['user']['fun_settings'].nil?
      pool = params['user']['fun_settings']
      pool.delete('0')
      array = pool.map { |id| id.to_i }
      user.update(fun_settings: array)
    elsif !params['user']['random_settings'].nil?
      pool = params['user']['random_settings']
      pool.delete('0')
      array = pool.map { |id| id.to_i }
      user.update(random_settings: array)
    end
    redirect_back(fallback_location: user_settings_path(current_user))
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/explanations/show.html.erb
<%= render partial: 'navs/main_nav' %>

<h2>Stat Pick</h2>
<p>The Stat Pick section of this site is the bulk of the current evaluative work being done by this app.</p>
<p>The Stat Pick is based on a 100 point system:</p>
<p>20 points come from the  current professional pick and ban rates for the hero</p>
<p>30 points come from the overall win rate of the hero across all levels of play</p>
<p>25 points come from the individual player's amount of experience with the hero</p>
<p>25 points come from the individual player's win rate with the hero</p>
<p>Each category has an initial value, like the win rate, games played, or number of picks and bans</p>
<p>These values are then placed into a group together and then clumped into smaller groups to allocate a point value</p>
<p>From this point system, a group of 10 top heroes is created, and one is randomly selected to be the stat pick</p>
<p>This final layer of randomization prevents the Stat Pick from being the same every time</p>

<h2>Fun Pick</h2>
<p>The Fun Pick section of this site is first and foremost, a user driven selection derived from heroes they find fun</p>
<p>In the settings page the user can set the hero pool from which they would like to play</p>
<p>From that fun hero pool, the user based statistics (experience and win rate for the user), are used to select a pick</p>

<h2>Random Pick</h2>
<p>The random pick section of this site is dedicated to allowing the user to have random picks selected for them</p>
<p>The value of this section is that in game, there is no way to both random a hero, while also avoiding certain others</p>
<p>In the User settings page, the user can select a pool of heroes that they do not want to random</p>
<p>By including as few heroes as possible, the user keeps this section as entertaining as they can</p>

app/views/heros/index.html.erb
<main>
  <h2>Current Hero Stats</h2>
  <%= link_to 'Update Heroes', heros_path, method: :post %>
  <div class='all-heroes'>
    <ul>
      <% @heroes.each do |hero| %>
        <div class='hero'>
        <li><img src=<%= hero.icon %>> <h3><%= hero.name %></h3></li>
        <li><p>Attribute: <%= hero.attr %></p></li>
        <li><p>Attack Type: <%= hero.range %></p></li>
        <li><p>Hero Id: <%= hero.hero_id %></p></li>
        <li><p>Pro Use: Pick or Ban in <%= hero.metrics['pro_participation'] %>% of games.
        <li><p>Pro Stats: <%= hero.pro_pick %> picks and <%= hero.pro_win %> wins, banned <%= hero.pro_ban %> times.</p></li>
        <li>
          <p>Pub Pick Breakdown:<p>
          <ul class='pick-breakdown'>
            <li><p>Picked first <%= hero.first_pick_percent %>% of the time, with a <%= hero.first_win_percent %>% win rate</p></li>
            <li><p>Picked second <%= hero.second_pick_percent %>% of the time, with a <%= hero.second_win_percent %>% win rate</p></li>
            <li><p>Picked third <%= hero.third_pick_percent %>% of the time, with a <%= hero.third_win_percent %>% win rate</p></li>
            <li><p>Picked fourth <%= hero.fourth_pick_percent %>% of the time, with a <%= hero.fourth_win_percent %>% win rate</p></li>
            <li><p>Picked fifth <%= hero.fifth_pick_percent %>% of the time, with a <%= hero.fifth_win_percent %>% win rate</p></li>
          </ul>
        </li>
        </div>
      <% end %>
    </ul>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
    <%= yield :chart_js %>
  </body>
</html>

app/views/login/index.html.erb
<main class='login'>
  <%= form_with(url: '/sessions', method: :post) do %>
    <%= email_field_tag(:email) %>

    <%= password_field_tag(:password) %>

    <%= submit_tag 'Login' %>
  <% end %>
</main>

app/views/matchups/index.html.erb
<h2>Hero Matchups</h2>
<table>
  <thead><th>Hero</th><th>Opponents</th>
  <tbody>
    <% @hero_matchups.data.each do |matchups| %>
    <div class='hero'>
    <tr>
      <td><img src=<%= matchups['hero'][0] %>><h3><%= matchups['hero'][1] %></h3></td>
      <% @hero_matchups.ids.each do |opponent| %>
        <% hero = Hero.find_by(hero_id: opponent) %>
        <td class='hero-matchup'><img src=<%= hero.icon %>><p><%= hero.name %>: <%= matchups[opponent] %>%</p></td>
      <% end %>
    </tr>
    </div>
    <% end %>
  </tbody>
</table>

app/views/navs/_main_nav.html.erb
<nav class='main_nav' %>
  <%= link_to 'Home', user_path(current_user) %>
  <%= link_to 'Explanations', explanations_path %>
  <%= link_to 'Settings', user_settings_path(current_user) %>
  <%= link_to 'Logout', logout_path %>
</nav>

app/views/settings/show.html.erb
<%= render partial: 'navs/main_nav' %>

<div class='settings'> 
  <div class='fun-settings'>
    <h1>Set Heroes to Include in the Fun Hero Selection</h1>
    <h3>Current Fun Heroes Include</h3>
    <div class='current-fun-settings'>
      <% @fun_heroes = Hero.where(hero_id: current_user.fun_settings) %>
      <ul>
        <% @fun_heroes.each do |hero| %>
          <li><img src=<%= hero.icon %>>
              <p><%= hero.name %></p>
          </li>
        <% end %>
      </ul>
    </div>
    <h3>Select New Fun Hero Pool</h3>
    <div class='new-fun-settings'>
      <%= form_for @user do |f| %>
        <% heroes = Hero.all %>
        <ul>
          <% heroes.each do |hero| %>
            <li><%= hero.name %>
                <%= f.check_box :fun_settings, { multiple: true }, hero.hero_id %>
            </li>
          <% end %>
        </ul>

        <%= f.submit %>
      <% end %>
    </div>
  </div>

  <div class='random-settings'>
    <h1>Set Heroes to Remove from the Random Hero Selection</h1>
    <h3>Currently Unincluded Heroes Include</h3>
    <div class='current-random-settings'>
      <% @random_heroes = Hero.where(hero_id: current_user.random_settings) %>
      <ul>
        <% @random_heroes.each do |hero| %>
          <li><img src=<%= hero.icon %>>
              <p><%= hero.name %></p>
          </li>
        <% end %>
      </ul>
    </div>
    <h3>Select New Unincluded Heroes</h3>
    <div class='new-random-settings'>
      <%= form_for @user do |f| %>
        <% heroes = Hero.all %>
        <ul>
          <% heroes.each do |hero| %>
            <li><%= hero.name %>
                <%= f.check_box :random_settings, { multiple: true }, hero.hero_id %>
            </li>
          <% end %>
        </ul>

        <%= f.submit %>
      <% end %>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<main class='new_user'>
  <%= form_for @user do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :steam_id %>
    <%= f.text_field :steam_id %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit %>

  <% end %>
</main>

app/views/users/show.html.erb
<%= render partial: 'navs/main_nav'%>
<main>
  <div class='setup'>
    <div class='user'>
      <h2>Welcome <%= @steam_user.name %>!</h2>
      <img src=<%= @steam_user.avatar %>>
      <p>Steam Id: <%= @steam_user.steam_id %><p>
      <p>Currently Playing As: <%= @steam_user.persona %></p>
      <p>Rank Tier: <%= @steam_user.rank_tier %></p>
      <p>MMR Estimate: <%= @steam_user.mmr %></p>
    </div>
    <div class='top-hero-stats'>
      <h2>Statistics for Your Top Heroes</h2>
      <% @hero = @steam_user.top_heroes.sample %>
      <div><canvas id="hero-stats" width="400" height="400"></canvas></div>
      <script>
        var ctx = document.getElementById("hero-stats").getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: <%= raw @steam_user.top_heroes_names.to_json %>,
                datasets: [{
                    label: 'Scores',
                    data: <%= raw @steam_user.top_heroes_scores.to_json %>,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:false,
                            autoSkip: false,
                            min: <%= @steam_user.top_heroes_scores.min - 5 %>
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            autoSkip: false
                        }
                    }]
                }
            }
        });
      </script>
    </div>
  </div>

  <div class='heroes'>
    <div class='stat-pick'>
      <% @hero = @steam_user.top_heroes.sample %>
      <h1>Stat Pick: <%= @hero.name %></h1>
      <img src=<%= @hero.image %>>
    </div>
    <div class='fun-pick'>
      <% unless @steam_user.fun_heroes.count == 0 || @steam_user.fun_heroes.nil? %>
        <% @fun_hero = @steam_user.fun_heroes.sample %>
        <h1>Fun Pick: <%= @fun_hero.name %></h1>
        <img src=<%= @fun_hero.image %>>
      <% else %>
        <% @fun_hero = @steam_user.random_heroes.sample %>
        <h1>Fun Pick: <%= @fun_hero.name %></h1>
        <img src=<%= @fun_hero.image %>>
      <% end %>
    </div>
    <div class='random-pick'>
      <% @random_hero = @steam_user.random_heroes.sample %>
      <h1>Random Pick: <%= @random_hero.name %></h1>
      <img src=<%= @random_hero.image %>>
    </div>
  </div>
</main>

app/views/welcome/index.html.erb
<main class='welcome_page'>
  <h1>Welcome to Pick-Me!</h1>
  <p>Pick-Me is a tool to enhance the pick selection process in the game of Dota2 by allowing users to have heroes suggested to them.</p>
  <p>Pick-Me will give users 3 prospective picks: one purely stat based, incorporating the users statistics, overall statistics, and professional statistics; one purely random, with the ability to remove certain heroes from the queue with user settings; and one 'fun' pick, which randomly selects a hero from a pool comprised of those that the user has the most experience and highest win rate with.</p>
  <p>To get started, click below to log into your Steam account, Pick-Me will only access your Dota2 statistics.</p>
  <div id='login-button'><%= link_to image_tag('steamIcon.png'), '/auth/steam' %></div>
  <div id='default-login'><%= link_to "Continue Without Logging In", '/dashboard' %></div>
</main>